import { ArrowUpRight, Search, Sparkles, X } from "lucide-react";
import type { Project } from "../lib/supabase";
import { categories, formatMoney } from "../lib/projects";
import { ProjectCard } from "../components/ProjectCard";
import { Progress, ProjectVisual } from "../components/ProjectPrimitives";

export function HomePage({ projects, activeCategory, query, onCategoryChange, onQueryChange, onProject, onDonate }: {
  projects: Project[]; activeCategory: typeof categories[number]; query: string;
  onCategoryChange: (category: typeof categories[number]) => void; onQueryChange: (query: string) => void;
  onProject: (project: Project) => void; onDonate: (project: Project) => void;
}) {
  const featured = projects[0];
  const visibleProjects = projects.filter((project) => {
    const matchesCategory = activeCategory === "All projects" || project.category === activeCategory;
    const haystack = `${project.title} ${project.church} ${project.location} ${project.category}`.toLowerCase();
    return matchesCategory && haystack.includes(query.toLowerCase());
  });
  if (!featured) return <main className="empty-state section-wrap"><Sparkles size={20} /><h3>No projects available</h3><p>Check back soon for new church projects.</p></main>;
  return <main id="top">
    <section className="hero section-wrap"><div className="hero-copy reveal reveal-one"><p className="eyebrow"><span className="eyebrow-dot" /> On-chain giving, human scale</p><h1>Fund the spaces<br /><em>where faith</em> comes alive.</h1><p className="hero-description">SoundFaith connects generous people with the church projects making room for more belonging, beauty, and voice.</p><div className="hero-actions"><a className="button button-coral" href="#/projects">Browse projects <ArrowUpRight size={16} /></a><a className="text-link" href="#/how-it-works">See how it works <span>↗</span></a></div></div><div className="hero-aside reveal reveal-two"><div className="hero-note"><span className="note-index">01</span><span>Small gifts.<br />Lasting echoes.</span></div><div className="hero-rule" /><p className="hero-aside-copy">Every project is verified by a local church team and every contribution is visible on Coreum.</p></div><div className="hero-stats reveal reveal-three"><div><strong>42</strong><span>projects funded</span></div><div><strong>$184k</strong><span>given by community</span></div><div className="chain-status"><span className="status-orbit"><span /></span><div><strong>Coreum</strong><span>testnet is live</span></div></div></div></section>
    <section className="feature-section section-wrap" id="projects"><div className="section-kicker"><span>Featured project</span><span className="kicker-line" /><span>01 / {String(projects.length).padStart(2, "0")}</span></div><div className="feature-layout"><ProjectVisual project={featured} featured /><article className="feature-panel"><div className="feature-panel-top"><span className="category-label">{featured.category}</span><span className="feature-location">{featured.location}</span></div><p className="feature-church">{featured.church}</p><h2>{featured.title}</h2><p className="feature-description">{featured.description}</p><div className="funding-detail"><div className="funding-numbers"><span><strong>{formatMoney(featured.raised)}</strong> raised</span><span>of {formatMoney(featured.goal)}</span></div><Progress project={featured} large /><div className="funding-footer"><span><b>{Math.round((featured.raised / featured.goal) * 100)}%</b> funded</span><span>{featured.donors} neighbors have given</span></div></div><button className="button button-coral feature-donate" onClick={() => onDonate(featured)}>Support this project <ArrowUpRight size={16} /></button></article></div></section>
    <section className="projects-section section-wrap"><div className="projects-heading"><div><p className="eyebrow">The project shelf</p><h2>Good work, <em>in progress.</em></h2></div><p className="projects-intro">Browse the practical, beautiful things churches are building together.</p></div><div className="project-toolbar"><div className="filter-tabs" role="tablist" aria-label="Project categories">{categories.map((category) => <button key={category} className={activeCategory === category ? "filter-tab active" : "filter-tab"} onClick={() => onCategoryChange(category)} role="tab" aria-selected={activeCategory === category}>{category}</button>)}</div><label className="search-field"><Search size={16} /><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Search projects" aria-label="Search projects" />{query && <button className="clear-search" onClick={() => onQueryChange("")} aria-label="Clear search"><X size={14} /></button>}</label></div><div className="project-grid">{visibleProjects.map((project, index) => <ProjectCard key={project.id} project={project} index={index} onDetails={() => onProject(project)} onDonate={() => onDonate(project)} />)}</div>{visibleProjects.length === 0 && <div className="empty-state"><Sparkles size={20} /><h3>No projects found</h3><p>Try another search or category.</p></div>}</section>
    <section className="promise-section section-wrap" id="how-it-works"><div className="promise-number">02</div><div><p className="eyebrow">The SoundFaith promise</p><h2>More than a transaction.<br /><em>A shared signal.</em></h2></div><p className="promise-copy">Your gift is a vote for the places that hold us. We make the path from intention to impact clear, accountable, and full of heart.</p><a className="text-link" href="#/churches">Our approach <span>↗</span></a></section>
  </main>;
}
