import { useEffect, useRef, useState, type ChangeEvent, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { ArrowLeft, ArrowUpRight, Bell, Check, Copy, Download, Eye, Moon, Pencil, RefreshCw, Sun, Wallet, X } from "lucide-react";
import { getViewerRole } from "../lib/admin";
import { identityRepository, type Notification } from "../lib/supabase";
import { getCoreumBalances } from "../lib/wallet";
import { createBrowserWallet, exportBrowserWallet, getBrowserWalletAddress, getBrowserWallets, hasBiometricUnlock, importBrowserWallet, importBrowserWalletMnemonic, importBrowserWalletPrivateKey, registerBiometricUnlock, removeBrowserWallet, revealBrowserWalletMnemonic, switchBrowserWallet } from "../lib/walletVault";

const chainExplorerBase = import.meta.env.VITE_COREUM_NETWORK === "mainnet" ? "https://explorer.coreum.com" : "https://explorer.testnet-1.coreum.dev";
type ProfileModal = "name" | "mnemonic" | "wallets" | "add-wallet" | null;
type ProfileData = { email?: string | null; wallet_address?: string | null; handle?: string | null; created_at?: string | null };
type WalletItem = { id: string; name: string; address: string };
type Theme = "light" | "dark";
type WalletAddMode = "choices" | "create" | "mnemonic" | "private-key" | "backup";

export function ProfilePage() {
  const [profile, setProfile] = useState<ProfileData | null>(null);
  const [role, setRole] = useState<"admin" | "reviewer" | null>(null);
  const [handleDraft, setHandleDraft] = useState("");
  const [balance, setBalance] = useState<number | null>(null);
  const [mnemonic, setMnemonic] = useState<string | null>(null);
  const [mnemonicRevealed, setMnemonicRevealed] = useState(false);
  const [mnemonicPassword, setMnemonicPassword] = useState("");
  const [wallets, setWallets] = useState<WalletItem[]>([]);
  const [walletName, setWalletName] = useState("");
  const [walletPassword, setWalletPassword] = useState("");
  const [restoreMnemonic, setRestoreMnemonic] = useState("");
  const [walletAddMode, setWalletAddMode] = useState<WalletAddMode>("choices");
  const [mnemonicLength, setMnemonicLength] = useState(12);
  const [mnemonicWords, setMnemonicWords] = useState<string[]>(Array(12).fill(""));
  const [privateKey, setPrivateKey] = useState("");
  const [backupFile, setBackupFile] = useState<File | null>(null);
  const [modal, setModal] = useState<ProfileModal>(null);
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(true);
  const [theme, setTheme] = useState<Theme>(() => window.localStorage.getItem("soundfaith-theme") === "dark" ? "dark" : "light");
  const [biometric, setBiometric] = useState(hasBiometricUnlock);
  const [mnemonicCopied, setMnemonicCopied] = useState(false);
  const [unreadNotifications, setUnreadNotifications] = useState<Notification[]>([]);

  const refresh = async () => {
    setLoading(true); setMessage("");
    try {
      const dashboard = await identityRepository.getDashboard();
      const [localAddress, localWallets, viewerRole, notifications] = await Promise.all([getBrowserWalletAddress(), getBrowserWallets(dashboard.profile?.email ?? undefined), getViewerRole(), identityRepository.getNotifications(0, 20)]);
      setProfile(dashboard.profile); setHandleDraft(dashboard.profile?.handle ?? ""); setWallets(localWallets); setRole(viewerRole);
      setUnreadNotifications(notifications.filter((item) => !item.read_at));
      const address = dashboard.profile?.wallet_address ?? localAddress;
      const balances = address ? await getCoreumBalances(address) : null;
      setBalance(balances?.native ?? null);
    } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load profile"); }
    finally { setLoading(false); }
  };

  useEffect(() => { void refresh(); }, []);
  useEffect(() => {
    if (!modal) return;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => { document.body.style.overflow = previousOverflow; };
  }, [modal]);
  const activeWallet = wallets.find((wallet) => wallet.address === profile?.wallet_address);
  const closeModal = () => { setModal(null); setMnemonic(null); setMnemonicRevealed(false); setMnemonicPassword(""); setWalletAddMode("choices"); setMnemonicLength(12); setMnemonicWords(Array(12).fill("")); setPrivateKey(""); setBackupFile(null); };
  const updateHandle = async () => { try { const updated = await identityRepository.updateProfileHandle(handleDraft); setProfile((current) => ({ ...(current ?? {}), handle: updated?.handle ?? handleDraft })); closeModal(); setMessage("User name updated."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to update user name"); } };
  const revealMnemonic = async () => { try { setMnemonic(await revealBrowserWalletMnemonic(mnemonicPassword)); setMnemonicRevealed(false); setMnemonicPassword(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to unlock mnemonic"); } };
  const switchWallet = async (id: string) => { try { const next = await switchBrowserWallet(id); await identityRepository.syncProfile(next.address); closeModal(); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to switch wallet"); } };
  const createWallet = async () => { try { await createBrowserWallet(walletPassword, walletName, profile?.email ?? undefined); setWalletName(""); setWalletPassword(""); closeModal(); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create wallet"); } };
  const restoreFromMnemonic = async () => { try { await importBrowserWalletMnemonic(restoreMnemonic, walletPassword, null, walletName || "Recovered wallet", profile?.email ?? undefined); setRestoreMnemonic(""); setWalletName(""); setWalletPassword(""); closeModal(); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to restore wallet"); } };
  const createFromMnemonic = async () => { try { await importBrowserWalletMnemonic(mnemonicWords.join(" "), walletPassword, null, walletName || "Recovered wallet", profile?.email ?? undefined); closeModal(); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to import mnemonic"); } };
  const importPrivateKey = async () => { try { await importBrowserWalletPrivateKey(privateKey, walletPassword, walletName || "Imported wallet", profile?.email ?? undefined); closeModal(); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to import private key"); } };
  const updateMnemonicLength = (length: number) => { setMnemonicLength(length); setMnemonicWords((current) => Array.from({ length }, (_, index) => current[index] ?? "")); };
  const pasteMnemonic = (event: React.ClipboardEvent<HTMLInputElement>) => { const pasted = event.clipboardData.getData("text").trim().split(/\s+/).filter(Boolean); if (pasted.length > 1) { event.preventDefault(); updateMnemonicLength(pasted.length); setMnemonicWords(pasted); } };
  const selectBackup = (event: ChangeEvent<HTMLInputElement>) => { setBackupFile(event.target.files?.[0] ?? null); event.target.value = ""; };
  const importBackup = async () => { if (!backupFile) return; try { await importBrowserWallet(backupFile, null, walletName || undefined, profile?.email ?? undefined); setWalletName(""); closeModal(); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to import wallet backup"); } };
  const copyMnemonic = async () => { if (mnemonic && mnemonicRevealed) { await navigator.clipboard.writeText(mnemonic); setMnemonicCopied(true); window.setTimeout(() => setMnemonicCopied(false), 2500); } };
  const exportWallet = async () => { try { await exportBrowserWallet(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to export wallet"); } };
  const toggleTheme = () => { const next = theme === "light" ? "dark" : "light"; setTheme(next); document.documentElement.dataset.theme = next; window.localStorage.setItem("soundfaith-theme", next); };
  const enableBiometric = async () => { try { await registerBiometricUnlock(); setBiometric(true); setMessage("Biometric unlock enabled on this device."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to enable biometric unlock"); } };
  const signOut = async () => { try { await identityRepository.signOut(); window.location.hash = "#/"; window.scrollTo(0, 0); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to sign out"); } };
  const removeWallet = async (id: string) => { if (!window.confirm("Remove this wallet from this device? The encrypted wallet backup will be deleted.")) return; try { await removeBrowserWallet(id); closeModal(); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to remove wallet"); } };
  const deleteAccount = async () => { if (!window.confirm("Delete your SoundFaith account? This cannot be undone.")) return; try { await identityRepository.deleteProfile(); await identityRepository.signOut(); window.location.hash = "#/"; window.scrollTo(0, 0); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to delete account"); } };
  const markNotificationRead = async (notification: Notification) => { if (notification.read_at) return; try { await identityRepository.markNotificationRead(notification.id); setUnreadNotifications((current) => current.filter((item) => item.id !== notification.id)); window.dispatchEvent(new Event("soundfaith-notifications-changed")); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to update notification"); } };

  return <main className="profile-page section-wrap">
    <div className="profile-page-heading"><div><p className="eyebrow">Your SoundFaith identity</p><h1>Your<br /><em>profile.</em></h1></div><button className="icon-button" onClick={() => void refresh()} aria-label="Refresh profile" title="Refresh profile"><RefreshCw size={16} /></button></div>
    {message && <p className="modal-footnote profile-message">{message}</p>}
    <section className="profile-section-card profile-notification-section"><div className="profile-section-title"><div><p className="eyebrow">Notifications</p><h2>{unreadNotifications.length ? "You have an update." : "Stay in the loop."}</h2></div><Bell size={20} /></div>{unreadNotifications[0] ? <article className="notification-card profile-notification-card" onClick={() => void markNotificationRead(unreadNotifications[0])}><div className="notification-card-icon"><Bell size={18} /></div><div className="notification-card-body"><strong>{unreadNotifications[0].title}</strong><span>{new Date(unreadNotifications[0].created_at).toLocaleString()}</span><p>{unreadNotifications[0].message}</p></div><div className="notification-card-meta"><span>Unread</span></div></article> : <p className="profile-empty">You are all caught up.</p>}<a className="button button-outline" href="#/notifications">Show notification history <ArrowUpRight size={15} /></a></section>
    <section className="profile-section-card profile-identity-card"><div className="profile-section-title"><div><p className="eyebrow">Account</p><h2>Login details</h2></div><button className="icon-button" onClick={() => setModal("name")} aria-label="Rename user" title="Rename user"><Pencil size={15} /></button></div><div className="profile-details-grid"><div><span>User name</span><strong>{profile?.handle ?? (loading ? "Loading..." : "Not assigned")}</strong></div>{role && <div><span>Role</span><strong><b className="role-badge">{role}</b></strong></div>}<div><span>Date joined</span><strong>{profile?.created_at ? new Date(profile.created_at).toLocaleDateString() : loading ? "Loading..." : "Not available"}</strong></div><div><span>Email address</span><strong>{profile?.email ?? (loading ? "Loading..." : "Not available")}</strong></div></div><p className="profile-privacy-note">SoundFaith does not store personal user data. The only account information retained for social login is your email address.</p></section>
    <section className="profile-section-card"><div className="profile-section-title"><div><p className="eyebrow">On this device</p><h2>Wallet details</h2></div><Wallet size={20} /></div><div className="profile-details-grid wallet-details-grid"><div><span>Wallet name</span><strong>{activeWallet?.name ?? "No wallet selected"}</strong></div><div><span>Address</span><strong className="account-wallet-address">{profile?.wallet_address ?? "Not configured"}</strong></div><div><span>TX balance</span><strong>{balance === null ? (loading ? "Loading..." : "--") : `${balance.toFixed(6)} TX`}</strong></div></div><div className="profile-button-row"><button className="button button-coral" onClick={() => setModal("wallets")}><Wallet size={15} /> Select wallet</button><button className="button button-dark" onClick={() => setModal("add-wallet")}><Wallet size={15} /> Add or create wallet</button><button className="button button-outline" onClick={() => void exportWallet()}><Download size={15} /> Export wallet</button><button className="button button-outline" onClick={() => setModal("mnemonic")}><Eye size={15} /> Show mnemonic</button></div><p className="profile-device-note">Wallet keys stay encrypted on this device. SoundFaith never receives your password or recovery phrase.</p></section>
    <section className="profile-section-card profile-settings-card"><div className="profile-section-title"><div><p className="eyebrow">Preferences & security</p><h2>Account settings</h2></div></div><div className="profile-settings-list"><button className="profile-setting" onClick={toggleTheme}><span><strong>Theme</strong><small>Choose how SoundFaith looks</small></span>{theme === "light" ? <Moon size={17} /> : <Sun size={17} />}</button><button className="profile-setting" onClick={() => void enableBiometric()}><span><strong>Biometric unlock</strong><small>{biometric ? "Enabled on this device" : "Use your device biometrics"}</small></span><span className={biometric ? "setting-status enabled" : "setting-status"}>{biometric ? "On" : "Off"}</span></button></div><div className="profile-account-actions"><button className="button button-outline" onClick={() => void signOut()}>Log out</button><button className="button button-danger" onClick={() => void deleteAccount()}>Delete account</button></div></section>
    {modal === "name" && <ProfileDialog title="Rename user" close={closeModal}><input className="profile-dialog-input" value={handleDraft} onChange={(event) => setHandleDraft(event.target.value)} placeholder="Your user name" /><button className="button button-coral modal-action" onClick={() => void updateHandle()} disabled={!handleDraft.trim()}>Save user name <ArrowUpRight size={15} /></button></ProfileDialog>}
    {modal === "mnemonic" && <ProfileDialog title="Show mnemonic" close={closeModal}><p className="modal-copy">Enter your wallet password. Your recovery phrase is decrypted locally and starts blurred.</p>{!mnemonic ? <><input className="profile-dialog-input" type="password" placeholder="Wallet password (12+ characters)" value={mnemonicPassword} onChange={(event) => setMnemonicPassword(event.target.value)} /><button className="button button-coral modal-action" onClick={() => void revealMnemonic()} disabled={!mnemonicPassword}>Unlock mnemonic <Eye size={15} /></button></> : <><div className={mnemonicRevealed ? "mnemonic-words revealed profile-dialog-mnemonic" : "mnemonic-words profile-dialog-mnemonic"}>{mnemonic.split(/\s+/).map((word, index) => <span className="mnemonic-word" key={`${word}-${index}`}><small>{index + 1}</small><b>{word}</b></span>)}</div><div className="profile-dialog-actions">{!mnemonicRevealed ? <button className="button button-dark" onClick={() => setMnemonicRevealed(true)}><Eye size={15} /> Show words</button> : <button className="icon-button" onClick={() => void copyMnemonic()} aria-label="Copy mnemonic" title="Copy mnemonic">{mnemonicCopied ? <Check size={15} /> : <Copy size={15} />}</button>}<button className="button button-outline" onClick={closeModal}>Done</button></div></>}</ProfileDialog>}
    {modal === "wallets" && <ProfileDialog title="Select wallet" close={closeModal}><div className="wallet-option-list">{wallets.map((wallet) => <div className={wallet.address === profile?.wallet_address ? "wallet-option-row active" : "wallet-option-row"} key={wallet.id}><button className="wallet-option" onClick={() => void switchWallet(wallet.id)}><strong>{wallet.name}</strong><small>{wallet.address}</small></button><button type="button" className="wallet-remove-button" onClick={() => void removeWallet(wallet.id)} aria-label={`Remove ${wallet.name}`} title="Remove wallet"><X size={15} /></button></div>)}</div>{!wallets.length && <p className="profile-empty">No wallets for this account on this device.</p>}<button className="button button-dark modal-action" onClick={() => { closeModal(); setModal("add-wallet"); }}>Add another wallet <Wallet size={15} /></button></ProfileDialog>}
    {modal === "add-wallet" && <ProfileDialog className={`wallet-add-dialog ${walletAddMode === "mnemonic" ? "wallet-mnemonic-dialog" : ""}`} title={walletAddMode === "choices" ? "Add or create wallet" : walletAddMode === "create" ? "Create new wallet" : walletAddMode === "mnemonic" ? "Import mnemonic" : walletAddMode === "private-key" ? "Import private key" : "Upload encrypted backup"} close={closeModal}><div className="wallet-flow">
      {walletAddMode === "choices" && <><p className="modal-copy">Choose how you want to add a TX blockchain wallet to this device.</p><div className="wallet-flow-choices"><button className="button button-coral" onClick={() => setWalletAddMode("create")}><Wallet size={15} /> Create new wallet</button><button className="button button-dark" onClick={() => setWalletAddMode("mnemonic")}>Import using mnemonic</button><button className="button button-dark" onClick={() => setWalletAddMode("private-key")}>Import using private key</button><button className="button button-outline" onClick={() => setWalletAddMode("backup")}>Upload encrypted backup</button></div></>}
      {walletAddMode === "create" && <><p className="modal-copy">A TX blockchain wallet will be created for you. The wallet and recovery phrase are saved only on this device. SoundFaith never receives them. Back up your mnemonic, keep it private, and never share it with anyone.</p><input className="profile-dialog-input" placeholder="Wallet name" value={walletName} onChange={(event) => setWalletName(event.target.value)} /><input className="profile-dialog-input" type="password" placeholder="Wallet password (12+ characters)" value={walletPassword} onChange={(event) => setWalletPassword(event.target.value)} /><button className="button button-coral modal-action" onClick={() => void createWallet()} disabled={walletPassword.length < 12}>Create wallet <Wallet size={15} /></button></>}
      {walletAddMode === "mnemonic" && <><div className="wallet-field-label">Number of words<div className="mnemonic-length-pills">{[12, 15, 18, 21, 24].map((length) => <button type="button" key={length} className={mnemonicLength === length ? "mnemonic-length-pill active" : "mnemonic-length-pill"} onClick={() => updateMnemonicLength(length)}>{length}</button>)}</div></div><div className="mnemonic-input-grid">{mnemonicWords.map((word, index) => <input className="profile-dialog-input" key={index} value={word} onPaste={index === 0 ? pasteMnemonic : undefined} onChange={(event) => setMnemonicWords((current) => current.map((entry, wordIndex) => wordIndex === index ? event.target.value : entry))} placeholder={`${index + 1}`} aria-label={`Mnemonic word ${index + 1}`} />)}</div><input className="profile-dialog-input" placeholder="Wallet name (optional)" value={walletName} onChange={(event) => setWalletName(event.target.value)} /><input className="profile-dialog-input" type="password" placeholder="New wallet password (12+ characters)" value={walletPassword} onChange={(event) => setWalletPassword(event.target.value)} /><button className="button button-coral modal-action" onClick={() => void createFromMnemonic()} disabled={mnemonicWords.some((word) => !word.trim()) || walletPassword.length < 12}>Import mnemonic <ArrowUpRight size={15} /></button></>}
      {walletAddMode === "private-key" && <><p className="modal-copy">Your private key is encrypted with the new wallet password and saved only on this device. Never share it with anyone.</p><input className="profile-dialog-textarea" value={privateKey} onChange={(event) => setPrivateKey(event.target.value)} placeholder="64-character hexadecimal private key" /><input className="profile-dialog-input" placeholder="Wallet name (optional)" value={walletName} onChange={(event) => setWalletName(event.target.value)} /><input className="profile-dialog-input" type="password" placeholder="New wallet password (12+ characters)" value={walletPassword} onChange={(event) => setWalletPassword(event.target.value)} /><button className="button button-coral modal-action" onClick={() => void importPrivateKey()} disabled={!privateKey.trim() || walletPassword.length < 12}>Import private key <ArrowUpRight size={15} /></button></>}
      {walletAddMode === "backup" && <><p className="modal-copy">Upload the encrypted wallet backup you imported before. You do not need to enter the wallet password here. The password is required later to unlock and sign with the wallet.</p><label className="wallet-upload-card"><Download size={20} /><strong>{backupFile ? backupFile.name : "Choose encrypted backup"}</strong><span>{backupFile ? "Backup selected. Import it to continue." : "Upload a SoundFaith wallet file from this device."}</span><input type="file" accept="application/json,.json" onChange={selectBackup} /></label><button className="button button-coral modal-action" onClick={() => void importBackup()} disabled={!backupFile}>Import backup <ArrowUpRight size={15} /></button></>}
      {walletAddMode !== "choices" && <button className="wallet-flow-back" onClick={() => setWalletAddMode("choices")}><ArrowLeft size={15} /> Back to wallet options</button>}
    </div></ProfileDialog>}
  </main>;
}

function ProfileDialog({ title, close, children, className = "" }: { title: string; close: () => void; children: ReactNode; className?: string }) {
  const [closing, setClosing] = useState(false);
  const touchStartY = useRef<number | null>(null);
  const touchDeltaY = useRef(0);
  const swipeClose = () => { setClosing(true); window.setTimeout(close, 220); };
  return createPortal(<div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><section className={`modal profile-dialog ${className}${closing ? " modal-closing" : ""}`.trim()} role="dialog" aria-modal="true" aria-labelledby="profile-dialog-title" onTouchStart={(event) => { touchStartY.current = event.touches[0]?.clientY ?? null; touchDeltaY.current = 0; }} onTouchMove={(event) => { if (touchStartY.current !== null) touchDeltaY.current = Math.max(0, (event.touches[0]?.clientY ?? touchStartY.current) - touchStartY.current); }} onTouchEnd={() => { if (touchDeltaY.current > 80) swipeClose(); touchStartY.current = null; touchDeltaY.current = 0; }}><button className="modal-close" onClick={close} aria-label="Close dialog"><X size={18} /></button><h2 id="profile-dialog-title">{title}</h2>{children}</section></div>, document.body);
}
